spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: trivia-service
server:
  port: '8100'

management:
  endpoints:
    web:
      exposure:
        include: refresh

feign:
  client:
    config:
      default:
#        connectTimeout: 5000
#        readTimeout: 5000
        loggerLevel: basic