spring:
  application:
    name: trivia-service
server:
  port: "8100"
management:
  endpoints:
    web:
      exposure:
        include: refresh
logging:
  level:
    project: DEBUG
feign:
  client:
    config:
      triviaQuestionsClient:
        url: https://the-trivia-api.com/api/questions
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
